# Generated by Django 4.0.4 on 2022-09-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber',
            new_name='subuser',
        ),
    ]
