# Generated by Django 4.0.4 on 2022-09-17 12:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_latest_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='latest_blog',
        ),
        migrations.RemoveField(
            model_name='blogherosection',
            name='blog_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='latest',
            field=models.BooleanField(default=False, null=True, verbose_name='latestBlog'),
        ),
        migrations.AddField(
            model_name='blogherosection',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='blogTitle'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='blogContent'),
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name_plural': 'Blog Meta Tag',
            },
        ),
    ]
