# Generated by Django 4.0.4 on 2022-09-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
    ]
