# Generated by Django 4.0.4 on 2022-09-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
